title: Make the camera follow a ball
hero_image: images/banner.png
description: Make the camera follow a ball
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Make the camera follow a ball
